### ISSUE TITLE
External payments agents fee

### ISSUE THREAD

**Issue by aprotopopov** [ibarchenkov/ndfl_dividents#2]
По какой-то причине следующее поле пропущено при парсинге CSV
> Сумма до удержания налога***

Когда удалил в xls/csv, переварило. Но я сам из pdf -> в xls перегонял без поддержки, может они присылают в другом формате. 

<img width="794" alt="image" src="https://user-images.githubusercontent.com/6563045/115156472-1a7a7d00-a08d-11eb-99cc-0e1066f6914d.png">

**Comment by ibarchenkov** [comment]
Мне поддержка Тинькова присылала .xlsx файл без колонки "Сумма до удержания налога", поэтому пришлось самому это вычислять.
Вообще я удивляюсь, что с такими ресурсами они не могут наладить какое-то автоматическое взаимодействие с налоговой, чтобы их клиентам не приходилось вручную заполнять эти данные или городить костыли как я.
